const GET_DIRECTOR_MAIL_LIST = "GET_DIRECTOR_MAIL_LIST"
const GET_NOTICE = 'GET_NOTICE'
const GET_SITE_INFO = 'GET_SITE_INFO'
export default{
    GET_DIRECTOR_MAIL_LIST,
    GET_NOTICE,
    GET_SITE_INFO,
}
